INSERT INTO TB_CATEGORIAS (DESCRICAO) VALUES ('Ação'),
('Aventura'),
('RPG (Role-Playing Game)'),
('Estratégia'),
('Simulação'),
('Esporte'),
('Corrida'),
('Terror / Horror'),
('Suspense'),
('Drama'),
('Comédia'),
('Ficção científica'),
('Fantasia'),
('Animação'),
('Documentário'),
('Musical'),
('Romance'),
('Guerra'),
('Faroeste (Western)'),
('Policial / Crime'),
('Mistério'),
('Sobrevivência (Survival)'),
('Mundo aberto (Open World)'),
('Battle Royale'),
('Plataforma'),
('Puzzle (Quebra-cabeça)'),
('Hack and Slash'),
('Stealth (Furtividade)'),
('MMO (Massively Multiplayer Online)'),
('Indie');